# Generated by Django 6.0.2 on 2026-03-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=20, unique=True, verbose_name='Identificación')),
                ('dv', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Dígito de verificación')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Razón Social')),
                ('trade_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Comercial')),
                ('names', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('legal_organization_id', models.PositiveIntegerField(verbose_name='Tipo de Organización Legal')),
                ('tribute_id', models.PositiveIntegerField(verbose_name='Responsabilidad Tributaria')),
                ('identification_document_id', models.PositiveIntegerField(verbose_name='Tipo de Documento')),
                ('municipality_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Municipio')),
            ],
        ),
    ]
