# Generated by Django 6.0.2 on 2026-03-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factus_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('address', models.CharField(max_length=200, verbose_name='Dirección')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('municipality_id', models.PositiveIntegerField(verbose_name='Municipio')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='identification',
            field=models.CharField(max_length=20, unique=True, verbose_name='Identificación * '),
        ),
        migrations.AlterField(
            model_name='customer',
            name='identification_document_id',
            field=models.PositiveIntegerField(verbose_name='Tipo de Documento *'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='legal_organization_id',
            field=models.PositiveIntegerField(verbose_name='Tipo de Organización Legal * '),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tribute_id',
            field=models.PositiveIntegerField(verbose_name='Responsabilidad Tributaria * '),
        ),
    ]
