# Generated by Django 6.0.2 on 2026-03-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factus_api', '0002_establishment_alter_customer_identification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_reference', models.CharField(max_length=200, unique=True, verbose_name='Código de Referencia')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('discount_rate', models.FloatField(default=0.0, verbose_name='Tasa de descuento')),
                ('price', models.FloatField(verbose_name='Precio')),
                ('tax_rate', models.CharField(max_length=50, verbose_name='Tasa de Impuesto')),
                ('unit_measure_id', models.PositiveBigIntegerField(verbose_name='Unidad de Medida')),
                ('standard_code_id', models.PositiveIntegerField(verbose_name='Código Estándar')),
                ('is_excluded', models.PositiveIntegerField(verbose_name='Excluido')),
                ('tribute_id', models.PositiveIntegerField(verbose_name='Tributo')),
                ('code', models.CharField(max_length=200, verbose_name='Código')),
                ('withholding_tax_rate', models.FloatField(verbose_name='Porcentaje de retención')),
            ],
        ),
    ]
